# Generated by Django 5.2.1 on 2025-07-09 08:21

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import location_field.models.plain
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('ID_camion', models.BigAutoField(primary_key=True, serialize=False)),
                ('Patente', models.CharField(blank=True, default=None, max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Destino', models.CharField(blank=True, default=None, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tipo_usuario', models.CharField(choices=[('Ad', 'Administrador'), ('Co', 'Conductor'), ('Cl', 'Cliente')], max_length=2)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(default='activo', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('ID_paquete', models.BigAutoField(primary_key=True, serialize=False)),
                ('Direccion', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('Destino', location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True)),
                ('Origen', models.CharField(choices=[('B1', 'Edmundo Larenas 160 Concepcion')], default=None, max_length=150)),
                ('Peso', models.PositiveIntegerField()),
                ('Dimensiones', models.CharField(choices=[('S', 'Pequeño'), ('M', 'Mediano'), ('L', 'Largo'), ('XL', 'Muy Largo')], default=None, max_length=2)),
                ('Instrucciones_Entrega', models.CharField(blank=True, default='', max_length=200)),
                ('Contenido', models.CharField(blank=True, default='', max_length=80)),
                ('Estado', models.CharField(choices=[('B', 'En bodega'), ('R', 'Repartiendo'), ('E', 'Entregado')], default=None, max_length=1)),
                ('Remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
