# Generated by Django 5.2.1 on 2025-05-30 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('ID_cliente', models.BigAutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('ID_paquete', models.BigAutoField(primary_key=True, serialize=False)),
                ('Direccion', models.CharField(max_length=200)),
                ('Peso', models.SmallIntegerField()),
                ('Instrucciones_Entrega', models.CharField(max_length=100)),
                ('Remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manejo_paquetes.cliente')),
            ],
        ),
    ]
