# Generated by Django 5.2.1 on 2025-06-11 08:07

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import location_field.models.plain
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('manejo_paquetes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('direccion', models.CharField(max_length=150)),
                ('tipo_usuario', models.CharField(choices=[('Ad', 'Administrador'), ('Co', 'Conductor'), ('Cl', 'Cliente')], max_length=2)),
                ('fecha_registro', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.CharField(default='A', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('ID_camion', models.BigAutoField(primary_key=True, serialize=False)),
                ('Patente', models.CharField(blank=True, default=None, max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('ID_entrega', models.BigAutoField(primary_key=True, serialize=False)),
                ('Destino', models.CharField(blank=True, default=None, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('ID_envio', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('ID_ruta', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='Nombre',
        ),
        migrations.RemoveField(
            model_name='paquete',
            name='Direccion',
        ),
        migrations.AddField(
            model_name='paquete',
            name='Contenido',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='paquete',
            name='Destino',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='paquete',
            name='Dimensiones',
            field=models.CharField(choices=[('S', 'Pequeño'), ('M', 'Mediano'), ('L', 'Largo'), ('XL', 'Muy Largo')], default=None, max_length=2),
        ),
        migrations.AddField(
            model_name='paquete',
            name='Estado',
            field=models.CharField(choices=[('B', 'En bodega'), ('R', 'Repartiendo'), ('E', 'Entregado')], default=None, max_length=1),
        ),
        migrations.AddField(
            model_name='paquete',
            name='Origen',
            field=models.CharField(choices=[('B1', 'Edmundo Larenas 160 Concepcion'), ('B2', 'Maipú 2120 Concepcion'), ('B3', 'Camilo Henríquez 2345 Concepcion'), ('B4', 'Arturo Prat 900 Concepcion')], default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='Instrucciones_Entrega',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='Peso',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('ID_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ID_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Lista_Paquetes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manejo_paquetes.entrega')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manejo_paquetes.paquete')),
            ],
        ),
        migrations.AddField(
            model_name='entrega',
            name='paquetes',
            field=models.ManyToManyField(through='manejo_paquetes.Lista_Paquetes', to='manejo_paquetes.paquete'),
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('ID_conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Camion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manejo_paquetes.camion')),
            ],
        ),
    ]
