# Generated by Django 5.2.1 on 2025-07-09 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manejo_paquetes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paquete',
            name='Remitente',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Paquete',
        ),
    ]
