# Generated by Django 5.2.1 on 2025-06-11 18:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manejo_paquetes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Envio',
        ),
        migrations.DeleteModel(
            name='Ruta',
        ),
        migrations.RemoveField(
            model_name='entrega',
            name='Destino',
        ),
        migrations.AddField(
            model_name='entrega',
            name='Conductor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manejo_paquetes.conductor'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='Estado',
            field=models.CharField(choices=[('P', 'Pendiente'), ('E', 'En camino'), ('C', 'Completada')], default='P', max_length=20),
        ),
        migrations.AddField(
            model_name='entrega',
            name='Fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='entrega',
            name='Fecha_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lista_paquetes',
            name='fecha_asignacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='Estado',
            field=models.CharField(choices=[('B', 'En bodega'), ('R', 'En reparto'), ('E', 'Entregado')], default='B', max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='lista_paquetes',
            unique_together={('entrega', 'paquete')},
        ),
    ]
