# Generated by Django 5.2.1 on 2025-06-01 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manejo_paquetes', '0002_auto_20250530_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('ID_usuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Correo', models.EmailField(max_length=254)),
                ('Contrasena', models.CharField(max_length=20)),
                ('Direccion', models.CharField(max_length=150)),
                ('Tipo_Usuario', models.CharField(choices=[('Ad', 'Administrador'), ('Co', 'Conductor'), ('Cl', 'Cliente')], max_length=2)),
                ('Fecha_Registro', models.DateField()),
                ('Estado', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('ID_camion', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('ID_envio', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('ID_ruta', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='Nombre',
        ),
        migrations.RemoveField(
            model_name='paquete',
            name='Direccion',
        ),
        migrations.AddField(
            model_name='paquete',
            name='Contenido',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='paquete',
            name='Destino',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='paquete',
            name='Dimensiones',
            field=models.CharField(choices=[('S', 'Pequeño'), ('M', 'Mediano'), ('L', 'Largo'), ('XL', 'Muy Largo')], default=None, max_length=2),
        ),
        migrations.AddField(
            model_name='paquete',
            name='Estado',
            field=models.CharField(choices=[('B', 'En bodega'), ('R', 'Repartiendo'), ('E', 'Entregado')], default=None, max_length=1),
        ),
        migrations.AddField(
            model_name='paquete',
            name='Origen',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='Instrucciones_Entrega',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('ID_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='manejo_paquetes.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('ID_conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='manejo_paquetes.usuario')),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ID_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='manejo_paquetes.usuario'),
        ),
        migrations.AddField(
            model_name='paquete',
            name='Envio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='manejo_paquetes.envio'),
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Camion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manejo_paquetes.camion')),
                ('Ruta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manejo_paquetes.ruta')),
                ('Conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manejo_paquetes.conductor')),
            ],
        ),
    ]
