# Generated by Django 5.2.1 on 2025-06-03 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manejo_paquetes', '0003_usuario_camion_envio_ruta_remove_cliente_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='Origen',
            field=models.CharField(choices=[('B1', 'Edmundo Larenas 160 Concepcion'), ('B2', 'Maipú 2120 Concepcion'), ('B3', 'Camilo Henríquez 2345 Concepcion'), ('B4', 'Arturo Prat 900 Concepcion')], default=None, max_length=150),
        ),
    ]
