# Generated by Django 5.2.1 on 2025-06-03 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manejo_paquetes', '0004_alter_paquete_origen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='Destino',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='Envio',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='manejo_paquetes.envio'),
        ),
    ]
