# Generated by Django 5.2.1 on 2025-06-03 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manejo_paquetes', '0005_alter_paquete_destino_alter_paquete_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='Peso',
            field=models.PositiveIntegerField(),
        ),
    ]
